// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa-iRaNJ_OwWEmBFTHFzjGizQOLLVMVx8',
    appId: '1:627007206659:web:f7600050d4d891dced6536',
    messagingSenderId: '627007206659',
    projectId: 'cartapp-80fc4',
    authDomain: 'cartapp-80fc4.firebaseapp.com',
    storageBucket: 'cartapp-80fc4.appspot.com',
    measurementId: 'G-5CCH0WG9DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUB2FbHXJUv5gihKfjkkh2DHRsT3fh0dY',
    appId: '1:627007206659:android:f9ce599591cb0358ed6536',
    messagingSenderId: '627007206659',
    projectId: 'cartapp-80fc4',
    storageBucket: 'cartapp-80fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXeQboEWz9MG3XMzZkPn-Py1YnEEF4Rg',
    appId: '1:627007206659:ios:e44d738b101a1e9aed6536',
    messagingSenderId: '627007206659',
    projectId: 'cartapp-80fc4',
    storageBucket: 'cartapp-80fc4.appspot.com',
    iosBundleId: 'com.example.cart',
  );
}
